//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swiss_Tournament.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swiss_Tournament.Language.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_games {
            get {
                return ResourceManager.GetString("count_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_participants {
            get {
                return ResourceManager.GetString("count_participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_remain_games {
            get {
                return ResourceManager.GetString("count_remain_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string create_date {
            get {
                return ResourceManager.GetString("create_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string remain_job {
            get {
                return ResourceManager.GetString("remain_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tab_participants_manage {
            get {
                return ResourceManager.GetString("tab_participants_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tab_round_manage {
            get {
                return ResourceManager.GetString("tab_round_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tab_summary {
            get {
                return ResourceManager.GetString("tab_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tab_tournament_manage {
            get {
                return ResourceManager.GetString("tab_tournament_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스위스 토너먼트 시뮬레이터과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
